tela4Linha0  : string "                                        "
tela4Linha1  : string "                                        "
tela4Linha2  : string "    PRESCIONE ENTER PARA INICIAR        "
tela4Linha3  : string "    E RECUPERAR O BARCO DO SIMOES       "
tela4Linha4  : string "                                        "
tela4Linha5  : string "                                        "
tela4Linha6  : string "                                        "
tela4Linha7  : string "~~~~~~~~~~~~~~~BBBBBBBB~~~~~~~~~~~~~~~~~"
tela4Linha8  : string "~~~~~~~~~~~~~~BBBBBBBBBB~~~~~~~~~~~~~~~~"
tela4Linha9  : string "~~~~~~~~~~~BBBBBBBBBBBBBBBB~~~~~~~~~~~~~"
tela4Linha10 : string "~~~~~~~~~~BBBBBBBBBBBBBBBBBB~~~~~~~~~~~~"
tela4Linha11 : string "~~~~~~~~~~BBBB   SIMÕES   BBB~~~~~~~~~~~"
tela4Linha12 : string "~~~~~~~~~~BBBBBBBBBBBBBBBBBB~~~~~~~~~~~~"
tela4Linha13 : string "~~~~~~~~~~~BBBBBBBBBBBBBBBB~~~~~~~~~~~~~"
tela4Linha14 : string "~~~~~~~~~~~~~~BBBBBBBBBB~~~~~~~~~~~~~~~~"
tela4Linha15 : string "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
tela4Linha16 : string "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
tela4Linha17 : string "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
tela4Linha18 : string "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
tela4Linha19 : string "~~~~~~~~~~~~~~~~~ __ ~~~~~~~~~~~~~~~~~~~"
tela4Linha20 : string "~~~~~~~~~~~~~~~  /  \  ~~~~~~~~~~~~~~~~~"
tela4Linha21 : string "~~~~~~~~~~~~~~~ /____\~~~~~~~~~~~~~~~~~~"
tela4Linha22 : string "~~~~~~~~~~~~~~~ \    /~~~~~~~~~~~~~~~~~~"
tela4Linha23 : string "~~~~~~~~~~~~~~~~~\__/~~~~~~~~~~~~~~~~~~~"
tela4Linha24 : string "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
tela4Linha25 : string "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
tela4Linha26 : string "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
tela4Linha27 : string "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
tela4Linha28 : string "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
tela4Linha29 : string "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
